version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0
    steps:
      - checkout
      - run:
          name: "Install Gems"
          command: bundle install
      - run:
          name: "Build Website"
          command: jekyll build
