name: Markdown Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**/*.md'
      - '.mdlrc'
      - '.markdownlint.yml'
      - '.github/workflows/markdownlint.yml'

permissions:
  contents: read
  pull-requests: write

jobs:
  markdownlint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v20
        continue-on-error: true
        with:
          config: '.markdownlint.yml'
          globs: '**/*.{md,markdown}'
